version: "3"
services:
  hub:
    image: seleniarm/hub:4.20
    ports:
    - 4444:4444
    # - 4442:4442
    # - 4443:4443
  chrome:
    image: seleniarm/node-chromium:4.20
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: seleniarm/node-firefox:4.20
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4